# Standards: 0.1
---
- name: Fact owncloud user
  set_fact:
    owncloud_user: "{{ owncloud_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - owncloud

- become: "{{ (owncloud_user != ansible_user_id) | bool }}"
  become_user: "{{ owncloud_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: owncloud
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - owncloud

- name: Remove quarantine flag
  register: owncloud_quarantine
  failed_when: owncloud_quarantine.rc != 0 and "No such xattr" not in owncloud_quarantine.stderr
  changed_when: owncloud_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/ownCloud.app
  tags:
    - owncloud

...
